version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "monday"
    time: "04:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 5
  target-branch: master
  reviewers:
  - suddenlyGiovanni
  labels:
  - dependencies
  - dependabot
  versioning-strategy: increase-if-necessary
  allow:
  - dependency-type: development
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
