develop version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    target_branch: 'develop'
    default_labels:
      - 'dependencies'
      - 'dependabot'
    commit_message:
      prefix: 'fix'
      prefix_development: 'chore'
      include_scope: true
    default_reviewers:
      - 'suddenlyGiovanni'
    allowed_updates:
      - match:
          dependency_type: 'development'
          # Supported dependency types:
          # - "development"
          #   Development dependency group (supported by some package managers)
          # - "production"
          #   Production dependency group (supported by some package managers)
          # - "direct"
          #   Direct/top-level dependencies
          # - "indirect"
          #   Indirect/transient/sub-dependencies
          # - "all"
          update_type: 'all'
          # Supported update types:
          # - "security"
          # - "all"
      - match:
          dependency_type: 'production'
          update_type: 'security'
    version_requirement_updates: 'increase_versions_if_necessary'
    automerged_updates:
      - match:
          dependency_type: 'development'
          # Supported dependency types:
          # - "development"
          # - "production"
          # - "all"
          update_type: 'semver:patch'
          # Supported updates to automerge:
          # - "security:patch"
          #   SemVer patch update that fixes a known security vulnerability
          # - "semver:patch"
          #   SemVer patch update, e.g. > 1.x && 1.0.1 to 1.0.3
          # - "semver:minor"
          #   SemVer minor update, e.g. > 1.x && 2.1.4 to 2.3.1
          # - "in_range"
          #   matching the version requirement in your package manifest
          # - "all"
      - match:
          # Wildcards match unlimited arbitrary characters (or none)
          dependency_name: 'typescript'
          update_type: 'all'
