# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - 'master'
      - 'develop' 
      - 'feature/**'
  pull_request:
    branches: 
      - 'master'
      - 'develop'
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Compile TypeScript
      run: yarn run build --if-present

    - name: Test source code
      run: yarn run test
      env:
        CI: true
    
